DROP DATABASE IF EXISTS locatordb;
DROP USER IF EXISTS `locatoradmin`@`%`;
CREATE DATABASE IF NOT EXISTS locatordb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `locatoradmin`@`%` IDENTIFIED WITH mysql_native_password by 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `locatordb`.* TO `locatoradmin`@`%`;